services:
  # A Docker web service
  - type: web
    name: restapi
    env: docker
    #repo: https://github.com/render-examples/webdis.git # optional
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    branch: master # optional (defaults to master)
    rootDir: restapi
    dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: lightning
          property: host # available properties are listed below
      - key: REDIS_PORT
        fromService:
          type: redis
          name: lightning
          property: port
      - fromGroup: conc-settings
  # A private Minio instance
